# Generated by Django 4.0.6 on 2023-04-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
