# Generated by Django 4.0.6 on 2023-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deposit_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
